Website/photosite/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

Website/photosite/photosite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [   
    path('scheduler/', include('scheduler.urls')),
    path('admin/', admin.site.urls),
]

Website/photosite/scheduler/urls.py
from django.urls import path

from . import views

app_name = 'scheduler'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:appointment_id>', views.view_appointment, name='view'),
    path('make', views.make_appointment, name='make'),
    path('cancel/<int:appointment_id>', views.cancel_appointment, name='cancel'),
    path('cancel_list', views.cancel_list, name='cancel_list')
]

Website/photosite/home/models.py
from django.db import models

# Create your models here.

Website/photosite/scheduler/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Appointment(models.Model):
    date = models.DateTimeField('Date signed up for')
    location = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    name = models.CharField(max_length=50, default="None")

    def appointment_soon(self):
        return self.date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self) -> str:
        return self.name

Website/photosite/home/views.py
from django.shortcuts import render

# Create your views here.

Website/photosite/scheduler/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, get_list_or_404
from django.urls import reverse
import datetime

from .models import Appointment
# Create your views here.
def index(request):
    #display the scheduler page
    error = None
    return render(request, 'scheduler/index.html', {'error':error, 'name':'', 'location':'','email':''})


def make_appointment(request):
    #make the appointment object
    appointment = Appointment()
    appointment.name = request.POST['name']
    appointment.location = request.POST['location']
    appointment.email = request.POST['email']
    appointment.date = request.POST['date']
    appointment.date = datetime.datetime.fromisoformat(appointment.date)
    #make sure no appointments are within 30 minutes of each other
    minuterange = 30
    prior = appointment.date + datetime.timedelta(minutes=-minuterange)
    end = appointment.date + datetime.timedelta(minutes=minuterange)
    conflicting_dates = Appointment.objects.filter(date__range=(prior, end))
    if conflicting_dates:
        #send error.
        return render(request, 'scheduler/index.html', {'error':"The date conflicts with another appointment. Please choose another appointment", 'name':appointment.name, 'location':appointment.location, 'email':appointment.email})
    #if no conflicts, save the date
    appointment.save()
    return render(request, 'scheduler/made.html')

def view_appointment(request, appointment_id):
    #get the appointment, and display it
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    return render(request, 'scheduler/view.html', {'appointment': appointment})

def cancel_appointment(request, appointment_id):
    #get the appointment
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    #remove appointment and display confirmation
    appointment.delete()
    return render(request, 'scheduler/canceled.html')

def cancel_list(request):
    #get the email from the form
    retreived_email = request.POST['email']
    #look for matching emails appointments, and display them
    appointments = Appointment.objects.filter(email=retreived_email)
    return render(request, 'scheduler/cancel_list.html', {'appointments':appointments})
    

Website/photosite/scheduler/templates/scheduler/cancel_list.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Appointments</title>
  </head>
  <body>
        {% if appointments %}
            <ul>
                {% for a in appointments %}
                    <li><a href="{% url 'scheduler:view' a.id %}">{{a.name}}</a></li>
                {% endfor %}
            </ul>
        {% else %}
        <p>No appointments were found with that email</p>
        {% endif %}
        <form action="{% url 'scheduler:cancel_list' %}" method="post">
            {% csrf_token %}
            <input type="email" placeholder="person@gmail.com" name="email" required="true">
            <input type="submit" name="search" value="Search appointments">
        </form>
  </body>
</html>

Website/photosite/scheduler/templates/scheduler/canceled.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Appointment canceled</title>
  </head>
  <body>
    <h1>Appointment canceled</h1>
    <div>Have a great day!</div>
    <a href="/scheduler">Back to appointments.</a>
  </body>
</html>

Website/photosite/scheduler/templates/scheduler/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Appointments</title>
  </head>
  <body>
    <h1>Schedule an Appointment</h1>
    {% if error %}
    <p>{{error}}</p>
    {% endif %}
    <form action="{% url 'scheduler:make' %}" method="post">
      {% csrf_token %}
      <input type="email" placeholder="person@gmail.com" value="{{ email }}" name="email" required="true">
      <input type="text" placeholder="name" name="name" value="{{ name }}" required="true">
      <input type="text" placeholder="location" name="location" value="{{ location }}" required="true">
      <input type="datetime-local" name="date" required="true">
      <input type="submit" name="schedule" value="schedule appointment">
    </form>
    <h1>Want to cancel an Appointment?</h1>
    <form action="{% url 'scheduler:cancel_list' %}" method="post">
      {% csrf_token %}
      <input type="email" placeholder="person@gmail.com" name="email" required="true">
      <input type="submit" name="search" value="Search appointments">
    </form>
  </body>
</html>

Website/photosite/scheduler/templates/scheduler/made.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Appointment made</title>
  </head>
  <body>
    <h1>Appointment made</h1>
    <div>Have a great day!</div>
    <a href="/scheduler">Back to appointments.</a>
  </body>
</html>

Website/photosite/scheduler/templates/scheduler/view.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>{{appointment}}'s appointment</title>
  </head>
  <body>
    <h1>Appointment for {{appointment}}</h1>
    <h2>Location: {{appointment.location}}</h2> 
    <h2>Time: {{appointment.date}}</h2>
    <h2>Email: {{appointment.email}}</h2>
    <form action="{% url 'scheduler:cancel' appointment.id %}" method="post">
        {% csrf_token %}
        <input type="submit" name="cancel" value="cancel appointment">
    </form>
  </body>
</html>